/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicProvablyFairImport } from './routes/_public/provably-fair'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as ProtectedCasinoImport } from './routes/_protected/casino'
import { Route as PublicProvablyFairUnhashServerSeedImport } from './routes/_public/provably-fair/unhash-server-seed'
import { Route as PublicProvablyFairCalculationImport } from './routes/_public/provably-fair/calculation'
import { Route as ProtectedCasinoMyBetsImport } from './routes/_protected/casino/my-bets'
import { Route as ProtectedCasinoHomeImport } from './routes/_protected/casino/home'
import { Route as ProtectedCasinoGamesImport } from './routes/_protected/casino/games'
import { Route as ProtectedCasinoGamesGameIdImport } from './routes/_protected/casino/games/$gameId'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicProvablyFairRoute = PublicProvablyFairImport.update({
  id: '/provably-fair',
  path: '/provably-fair',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const ProtectedCasinoRoute = ProtectedCasinoImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => ProtectedRoute,
} as any)

const PublicProvablyFairUnhashServerSeedRoute =
  PublicProvablyFairUnhashServerSeedImport.update({
    id: '/unhash-server-seed',
    path: '/unhash-server-seed',
    getParentRoute: () => PublicProvablyFairRoute,
  } as any)

const PublicProvablyFairCalculationRoute =
  PublicProvablyFairCalculationImport.update({
    id: '/calculation',
    path: '/calculation',
    getParentRoute: () => PublicProvablyFairRoute,
  } as any)

const ProtectedCasinoMyBetsRoute = ProtectedCasinoMyBetsImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => ProtectedCasinoRoute,
} as any)

const ProtectedCasinoHomeRoute = ProtectedCasinoHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedCasinoRoute,
} as any)

const ProtectedCasinoGamesRoute = ProtectedCasinoGamesImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => ProtectedCasinoRoute,
} as any)

const ProtectedCasinoGamesGameIdRoute = ProtectedCasinoGamesGameIdImport.update(
  {
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => ProtectedCasinoGamesRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_protected/casino': {
      id: '/_protected/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof ProtectedCasinoImport
      parentRoute: typeof ProtectedImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/provably-fair': {
      id: '/_public/provably-fair'
      path: '/provably-fair'
      fullPath: '/provably-fair'
      preLoaderRoute: typeof PublicProvablyFairImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_protected/casino/games': {
      id: '/_protected/casino/games'
      path: '/games'
      fullPath: '/casino/games'
      preLoaderRoute: typeof ProtectedCasinoGamesImport
      parentRoute: typeof ProtectedCasinoImport
    }
    '/_protected/casino/home': {
      id: '/_protected/casino/home'
      path: '/home'
      fullPath: '/casino/home'
      preLoaderRoute: typeof ProtectedCasinoHomeImport
      parentRoute: typeof ProtectedCasinoImport
    }
    '/_protected/casino/my-bets': {
      id: '/_protected/casino/my-bets'
      path: '/my-bets'
      fullPath: '/casino/my-bets'
      preLoaderRoute: typeof ProtectedCasinoMyBetsImport
      parentRoute: typeof ProtectedCasinoImport
    }
    '/_public/provably-fair/calculation': {
      id: '/_public/provably-fair/calculation'
      path: '/calculation'
      fullPath: '/provably-fair/calculation'
      preLoaderRoute: typeof PublicProvablyFairCalculationImport
      parentRoute: typeof PublicProvablyFairImport
    }
    '/_public/provably-fair/unhash-server-seed': {
      id: '/_public/provably-fair/unhash-server-seed'
      path: '/unhash-server-seed'
      fullPath: '/provably-fair/unhash-server-seed'
      preLoaderRoute: typeof PublicProvablyFairUnhashServerSeedImport
      parentRoute: typeof PublicProvablyFairImport
    }
    '/_protected/casino/games/$gameId': {
      id: '/_protected/casino/games/$gameId'
      path: '/$gameId'
      fullPath: '/casino/games/$gameId'
      preLoaderRoute: typeof ProtectedCasinoGamesGameIdImport
      parentRoute: typeof ProtectedCasinoGamesImport
    }
  }
}

// Create and export the route tree

interface ProtectedCasinoGamesRouteChildren {
  ProtectedCasinoGamesGameIdRoute: typeof ProtectedCasinoGamesGameIdRoute
}

const ProtectedCasinoGamesRouteChildren: ProtectedCasinoGamesRouteChildren = {
  ProtectedCasinoGamesGameIdRoute: ProtectedCasinoGamesGameIdRoute,
}

const ProtectedCasinoGamesRouteWithChildren =
  ProtectedCasinoGamesRoute._addFileChildren(ProtectedCasinoGamesRouteChildren)

interface ProtectedCasinoRouteChildren {
  ProtectedCasinoGamesRoute: typeof ProtectedCasinoGamesRouteWithChildren
  ProtectedCasinoHomeRoute: typeof ProtectedCasinoHomeRoute
  ProtectedCasinoMyBetsRoute: typeof ProtectedCasinoMyBetsRoute
}

const ProtectedCasinoRouteChildren: ProtectedCasinoRouteChildren = {
  ProtectedCasinoGamesRoute: ProtectedCasinoGamesRouteWithChildren,
  ProtectedCasinoHomeRoute: ProtectedCasinoHomeRoute,
  ProtectedCasinoMyBetsRoute: ProtectedCasinoMyBetsRoute,
}

const ProtectedCasinoRouteWithChildren = ProtectedCasinoRoute._addFileChildren(
  ProtectedCasinoRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedCasinoRoute: typeof ProtectedCasinoRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCasinoRoute: ProtectedCasinoRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicProvablyFairRouteChildren {
  PublicProvablyFairCalculationRoute: typeof PublicProvablyFairCalculationRoute
  PublicProvablyFairUnhashServerSeedRoute: typeof PublicProvablyFairUnhashServerSeedRoute
}

const PublicProvablyFairRouteChildren: PublicProvablyFairRouteChildren = {
  PublicProvablyFairCalculationRoute: PublicProvablyFairCalculationRoute,
  PublicProvablyFairUnhashServerSeedRoute:
    PublicProvablyFairUnhashServerSeedRoute,
}

const PublicProvablyFairRouteWithChildren =
  PublicProvablyFairRoute._addFileChildren(PublicProvablyFairRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicProvablyFairRoute: typeof PublicProvablyFairRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicProvablyFairRoute: PublicProvablyFairRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/casino': typeof ProtectedCasinoRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/provably-fair': typeof PublicProvablyFairRouteWithChildren
  '/': typeof PublicIndexRoute
  '/casino/games': typeof ProtectedCasinoGamesRouteWithChildren
  '/casino/home': typeof ProtectedCasinoHomeRoute
  '/casino/my-bets': typeof ProtectedCasinoMyBetsRoute
  '/provably-fair/calculation': typeof PublicProvablyFairCalculationRoute
  '/provably-fair/unhash-server-seed': typeof PublicProvablyFairUnhashServerSeedRoute
  '/casino/games/$gameId': typeof ProtectedCasinoGamesGameIdRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedRouteWithChildren
  '/casino': typeof ProtectedCasinoRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/provably-fair': typeof PublicProvablyFairRouteWithChildren
  '/': typeof PublicIndexRoute
  '/casino/games': typeof ProtectedCasinoGamesRouteWithChildren
  '/casino/home': typeof ProtectedCasinoHomeRoute
  '/casino/my-bets': typeof ProtectedCasinoMyBetsRoute
  '/provably-fair/calculation': typeof PublicProvablyFairCalculationRoute
  '/provably-fair/unhash-server-seed': typeof PublicProvablyFairUnhashServerSeedRoute
  '/casino/games/$gameId': typeof ProtectedCasinoGamesGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/casino': typeof ProtectedCasinoRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/provably-fair': typeof PublicProvablyFairRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_protected/casino/games': typeof ProtectedCasinoGamesRouteWithChildren
  '/_protected/casino/home': typeof ProtectedCasinoHomeRoute
  '/_protected/casino/my-bets': typeof ProtectedCasinoMyBetsRoute
  '/_public/provably-fair/calculation': typeof PublicProvablyFairCalculationRoute
  '/_public/provably-fair/unhash-server-seed': typeof PublicProvablyFairUnhashServerSeedRoute
  '/_protected/casino/games/$gameId': typeof ProtectedCasinoGamesGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/casino'
    | '/login'
    | '/provably-fair'
    | '/'
    | '/casino/games'
    | '/casino/home'
    | '/casino/my-bets'
    | '/provably-fair/calculation'
    | '/provably-fair/unhash-server-seed'
    | '/casino/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/casino'
    | '/login'
    | '/provably-fair'
    | '/'
    | '/casino/games'
    | '/casino/home'
    | '/casino/my-bets'
    | '/provably-fair/calculation'
    | '/provably-fair/unhash-server-seed'
    | '/casino/games/$gameId'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/casino'
    | '/_public/login'
    | '/_public/provably-fair'
    | '/_public/'
    | '/_protected/casino/games'
    | '/_protected/casino/home'
    | '/_protected/casino/my-bets'
    | '/_public/provably-fair/calculation'
    | '/_public/provably-fair/unhash-server-seed'
    | '/_protected/casino/games/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/_public"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/casino"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/login",
        "/_public/provably-fair",
        "/_public/"
      ]
    },
    "/_protected/casino": {
      "filePath": "_protected/casino.jsx",
      "parent": "/_protected",
      "children": [
        "/_protected/casino/games",
        "/_protected/casino/home",
        "/_protected/casino/my-bets"
      ]
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_public/provably-fair": {
      "filePath": "_public/provably-fair.tsx",
      "parent": "/_public",
      "children": [
        "/_public/provably-fair/calculation",
        "/_public/provably-fair/unhash-server-seed"
      ]
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_protected/casino/games": {
      "filePath": "_protected/casino/games.tsx",
      "parent": "/_protected/casino",
      "children": [
        "/_protected/casino/games/$gameId"
      ]
    },
    "/_protected/casino/home": {
      "filePath": "_protected/casino/home.tsx",
      "parent": "/_protected/casino"
    },
    "/_protected/casino/my-bets": {
      "filePath": "_protected/casino/my-bets.tsx",
      "parent": "/_protected/casino"
    },
    "/_public/provably-fair/calculation": {
      "filePath": "_public/provably-fair/calculation.tsx",
      "parent": "/_public/provably-fair"
    },
    "/_public/provably-fair/unhash-server-seed": {
      "filePath": "_public/provably-fair/unhash-server-seed.tsx",
      "parent": "/_public/provably-fair"
    },
    "/_protected/casino/games/$gameId": {
      "filePath": "_protected/casino/games/$gameId.tsx",
      "parent": "/_protected/casino/games"
    }
  }
}
ROUTE_MANIFEST_END */
