/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as ProtectedCasinoImport } from './routes/_protected/casino'
import { Route as ProtectedCasinoHomeImport } from './routes/_protected/casino.home'
import { Route as ProtectedCasinoGamesImport } from './routes/_protected/casino.games'
import { Route as ProtectedCasinoGamesDiceImport } from './routes/_protected/casino/games/dice'
import { Route as ProtectedCasinoGamesGameIdImport } from './routes/_protected/casino/games/$gameId'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const ProtectedCasinoRoute = ProtectedCasinoImport.update({
  path: '/casino',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedCasinoHomeRoute = ProtectedCasinoHomeImport.update({
  path: '/home',
  getParentRoute: () => ProtectedCasinoRoute,
} as any)

const ProtectedCasinoGamesRoute = ProtectedCasinoGamesImport.update({
  path: '/games',
  getParentRoute: () => ProtectedCasinoRoute,
} as any)

const ProtectedCasinoGamesDiceRoute = ProtectedCasinoGamesDiceImport.update({
  path: '/dice',
  getParentRoute: () => ProtectedCasinoGamesRoute,
} as any)

const ProtectedCasinoGamesGameIdRoute = ProtectedCasinoGamesGameIdImport.update(
  {
    path: '/$gameId',
    getParentRoute: () => ProtectedCasinoGamesRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_protected/casino': {
      id: '/_protected/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof ProtectedCasinoImport
      parentRoute: typeof rootRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/casino/games': {
      id: '/_protected/casino/games'
      path: '/games'
      fullPath: '/casino/games'
      preLoaderRoute: typeof ProtectedCasinoGamesImport
      parentRoute: typeof ProtectedCasinoImport
    }
    '/_protected/casino/home': {
      id: '/_protected/casino/home'
      path: '/home'
      fullPath: '/casino/home'
      preLoaderRoute: typeof ProtectedCasinoHomeImport
      parentRoute: typeof ProtectedCasinoImport
    }
    '/_protected/casino/games/$gameId': {
      id: '/_protected/casino/games/$gameId'
      path: '/$gameId'
      fullPath: '/casino/games/$gameId'
      preLoaderRoute: typeof ProtectedCasinoGamesGameIdImport
      parentRoute: typeof ProtectedCasinoGamesImport
    }
    '/_protected/casino/games/dice': {
      id: '/_protected/casino/games/dice'
      path: '/dice'
      fullPath: '/casino/games/dice'
      preLoaderRoute: typeof ProtectedCasinoGamesDiceImport
      parentRoute: typeof ProtectedCasinoGamesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PublicRoute: PublicRoute.addChildren({ PublicLoginRoute }),
  ProtectedCasinoRoute: ProtectedCasinoRoute.addChildren({
    ProtectedCasinoGamesRoute: ProtectedCasinoGamesRoute.addChildren({
      ProtectedCasinoGamesGameIdRoute,
      ProtectedCasinoGamesDiceRoute,
    }),
    ProtectedCasinoHomeRoute,
  }),
  ProtectedIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public",
        "/_protected/casino",
        "/_protected/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/login"
      ]
    },
    "/_protected/casino": {
      "filePath": "_protected/casino.tsx",
      "children": [
        "/_protected/casino/games",
        "/_protected/casino/home"
      ]
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx"
    },
    "/_protected/casino/games": {
      "filePath": "_protected/casino.games.tsx",
      "parent": "/_protected/casino",
      "children": [
        "/_protected/casino/games/$gameId",
        "/_protected/casino/games/dice"
      ]
    },
    "/_protected/casino/home": {
      "filePath": "_protected/casino.home.tsx",
      "parent": "/_protected/casino"
    },
    "/_protected/casino/games/$gameId": {
      "filePath": "_protected/casino/games/$gameId.tsx",
      "parent": "/_protected/casino/games"
    },
    "/_protected/casino/games/dice": {
      "filePath": "_protected/casino/games/dice.tsx",
      "parent": "/_protected/casino/games"
    }
  }
}
ROUTE_MANIFEST_END */
